### ISSUE TITLE
Adding constraints spanning multiple `NOT NULL` columns can fail unexpectedly

### ISSUE THREAD

**Issue by andrew-farries** [xataio/pgroll#830]
Running a `create_constraint` operation that spans multiple columns can fail if the spanned columns are `NOT NULL` due to the ordering of the `up` triggers for each column.

## Reproduction

1. Apply this migration to create an `items` table:

```yaml
operations:
  - create_table:
      name: items
      columns:
        - name: id
          type: serial
          pk: true
        - name: vendor
          type: text
        - name: name
          type: text
```

2. Insert some data into the table:

```sql
insert into items(vendor, name) values ('acme', 'banana')
```

3. Apply this `create_constraint` migration:

```yaml
operations:
  - create_constraint:
      type: check
      table: items
      name: check_vendor_name
      columns:
        - vendor
        - name
      check: length(name) >= length(vendor)
      up:
        vendor: vendor
        name: name || '_' || vendor
      down:
        vendor: vendor
        name: name
```

Running the second migration will fail with:

```
Error: unable to backfill table "items": pq: new row for relation "items" violates check constraint "_pgroll_dup__pgroll_check_not_null_name"
```

## Cause

The `create_constraint` operation creates two `up` triggers on the `items` table (it also creates two `down` triggers, but those aren't relevant here):

```
| public | _pgroll_trigger_items_name               | trigger          |                     | trigger |
| public | _pgroll_trigger_items_vendor             | trigger          |                     | trigger |
```

They are defined on the `items` table like this:

```
    _pgroll_trigger_items_name BEFORE INSERT OR UPDATE ON items FOR EACH ROW EXECUTE FUNCTION _pgroll_trigger_items_name()
    _pgroll_trigger_items_vendor BEFORE INSERT OR UPDATE ON items FOR EACH ROW EXECUTE FUNCTION _pgroll_trigger_items_vendor()
```

The trigger functions are defined like this:

**_pgroll_trigger_items_name**:

```sql
DECLARE
  "id" "public"."items"."id"%TYPE := NEW."id";
  "name" "public"."items"."name"%TYPE := NEW."name";
  "vendor" "public"."items"."_pgroll_new_vendor"%TYPE := NEW."_pgroll_new_vendor";
  latest_schema text;
  search_path text;
BEGIN
  SELECT current_setting
    INTO search_path
    FROM current_setting('search_path');

  IF search_path != 'public_02_create_constraint' THEN
    NEW."_pgroll_new_name" = (name || '_' || vendor);
    NEW."_pgroll_needs_backfill" = false;
  END IF;

  RETURN NEW;
END;
```

**pgroll_trigger_items_vendor**:

```sql
DECLARE
  "id" "public"."items"."id"%TYPE := NEW."id";
  "name" "public"."items"."name"%TYPE := NEW."name";
  "vendor" "public"."items"."vendor"%TYPE := NEW."vendor";
  latest_schema text;
  search_path text;
BEGIN
  SELECT current_setting
    INTO search_path
    FROM current_setting('search_path');

  IF search_path != 'public_02_create_constraint' THEN
    NEW."_pgroll_new_vendor" = (vendor);
    NEW."_pgroll_needs_backfill" = false;
  END IF;

  RETURN NEW;
END;
```

Because both triggers defined for the same event on the same relation they execute in alphabetical order (see the [Postgres trigger docs](https://www.postgresql.org/docs/current/trigger-definition.html)). 

* This means `_pgroll_trigger_items_name` executes before `_pgroll_trigger_items_vendor`.
* When `_pgroll_trigger_items_name` executes, `_pgroll_new_vendor` is still `NULL` for the row.
* In the assignment `NEW."_pgroll_new_name" = (name || '_' || vendor);`, the RHS evaluates to `NULL` because the `vendor` variable is `NULL`.
* The insert of the `NULL` value into `_pgroll_new_name` fails due to the `NOT NULL` constraint on the column.

This dependency where we have two triggers, but one requires the other to have set a `NEW.*` value (`NEW."_pgroll_new_vendor` in this example) before it executes is a general problem whenever a migration creates two interdependent `up` or `down` triggers.
