### ISSUE TITLE
Preserve primary key constraint on altered columns

### ISSUE THREAD

**Issue by kvch** [xataio/pgroll#888]
If a column with a primary key constraint on it is altered by `pgroll`, the primary key constraint is lost after completing the operation.

Migration to reproduce the issue:

```yaml
operations:
- alter_column:
    column: myid
    down: "CAST(\"myid\" AS bigint)"
    table: my_table
    type: uuid
    up: "gen_random_uuid"
```

Broken schema:
```
# \d my_table;
                    Table "public.my_table"
  Column   |           Type           | Collation | Nullable | Default
-----------+--------------------------+-----------+----------+---------
 myid      | uuid                     |           | not null |
Indexes:
    "my_table_pkey" UNIQUE, btree ("myid")
```

The primary key constraint is missing.

### Workaround

Run a second migration to apply primary key constraint again:
```yaml
operations:
- create_constraint:
    name: my_table_pk
    columns: [myid]
    table: my_table
    up:
      myid: myid
    down:
      myid: myid
```
