### ISSUE TITLE
How to proceed when database has stored procedures or functions ?

### ISSUE THREAD

**Issue by xfischer** [xataio/pgroll#936]
Hi, I have a database where a "users" table resides (same as pgroll tutorial).
There is also a stored procedure, 

```sql
CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  description TEXT
);

create or replace procedure setfakename(p_id int)
language plpgsql
as $$
begin
  update users set name = "fake" where id = p_id;
end;
$$;
```

Now, I want to have a firstname and lastname for my users, and remove the name column.

```
pgroll init
pgroll baseline 01_baseline usersdb
```

my db is now ready for the first change.

```yaml
# 02_username.yaml file
operations:
  - add_column:
      table: users
      up: name
      column:
        name: firstname
        type: VARCHAR(255)
        nullable: false
        unique: false
        pk: false
  - add_column:
      table: users
      up: null
      column:
        name: lastname
        type: VARCHAR(255)
        nullable: true
        unique: false
        pk: false
  - drop_column:
      table: users
      column: name
      down: firstname
```
I start this migration using `pgroll start usersdb\02_username.yaml`

I see the new users table ready in the 02_isactive schema.
How do I proceed with pgroll to update my procedure this way ?
```sql
SET search_path = 02_username, public;
CREATE OR REPLACE PROCEDURE setfakename(
	IN p_id integer)
LANGUAGE 'plpgsql'
AS $$
begin
  update users set firstname = "fake firstname", lastname = "fake lastname" where id = p_id;
end;
$$;
```

Now I want to prepare my nextgen app to use the new users table, and would like to define the procedure using pgroll. I could run a raw SQL migration, but I would need to complete the previous one which would break my old application.

Is there a way around this ?
Thanks!

**Comment by andrew-farries** [comment]
Hi, thanks for opening the issue.

Right now, I don't see a good way to work around this. Ideally, you'd be able to write this migration:

```yaml
operations:
  - sql:
      up: |-
        CREATE OR REPLACE PROCEDURE setfakename(
          IN p_id integer)
        LANGUAGE 'plpgsql'
        AS $$
        begin
          update users set firstname = 'fake firstname', lastname = 'fake lastname' where id = p_id;
        end;
        $$;
  - add_column:
      table: users
      column:
        name: firstname
        type: VARCHAR(255)
        nullable: false
        unique: false
        pk: false
      up: name
  - add_column:
      table: users
      column:
        name: lastname
        type: VARCHAR(255)
        nullable: true
        unique: false
        pk: false
      up: null
  - drop_column:
      table: users
      column: name
      down: firstname
```

ie, the same migration as you have above, but with a `sql` operation at the start to create the new version of the `setfakename` procedure.

Currently this isn't possible due to the limitation that `sql` operations have to be run in isolation; they can't appear in migrations alongside other operations.

https://github.com/xataio/pgroll/issues/943 tracks removing the limitation around running `sql` operations with other types of operations.
